server:
  port: 8081

spring:
  application:
    name: viago-admin-services

auth-service:
  base-url: http://localhost:8080
  admin-token: ${AUTH_SERVICE_TOKEN:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

