spring :
  datasource:
    url : ${DB_URL}${DB_NAME}
    username : ${DB_USERNAME}
    password : ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa :
    hibernate :
      ddl-auto : update

  jwt:
    secret: ${JWT_SECRET}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email

user-service:
  url: ${USER_SERVICE_URL:http://localhost}
  port: ${USER_SERVICE_PORT:8081}


#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: user-signup-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#
#  mail:
#    host: smtp.ethereal.email
#    port: 2525
#    username: conner.homenick25@ethereal.email
#    password: FvrgrmphQkk4XrFyGj
#    properties:
#      mail:
#        smtp:
#          auth:true
#        starttls:
#          enable:true
#
#  app:
#    kafka:
#      topic:
#        user-signup: user-signup-topic