spring :
  application:
    name: viago-auth-service
  profiles :
    active : cloud
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server :
  port : ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/