name: Deploy Admin Service

on:
  push:
    branches: [deploy-final]
    paths:
      - "viago-admin-services/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Build Admin Service
        run: |
          cd viago-admin-services
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/viago-admin-services:latest ./viago-admin-services
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/viago-admin-services:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/viago-admin-services:latest
            docker stop viago-admin-services || true
            docker rm viago-admin-services || true


            docker run -d \
              --name viago-admin-services \
              --network viago-net \
              -p 8081:8081 \
              ${{ secrets.DOCKERHUB_USERNAME }}/viago-admin-services:latest
